xmr address for donations: 46phznNsREX7MX1PukLkL6NA1U8e5XA1t9a5Ui22tTzDeGcNnUc6o2P7cFYQzmVnadCtMG7HfUHymUzR9zm5aU79KgKJvRL

Send your name with donation!!! I will list your name with a very special thank you and a special command for you!

I love to support Monero so please if you have the time, lets help each other support Monero and improve this community!
